// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTextSplit from '@/components/sections/about/AboutTextSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutTextSplit
          title="Our Design Philosophy"
          descriptions={[
            "Elara creates pieces that celebrate the unique silhouette of the wearer, blending traditional tailoring techniques with contemporary, fluid design.",
            "Every garment is a story of craftsmanship, from selecting the finest silks to the final delicate hand-stitched detailing in our atelier.",
            "Driven by a passion for sustainability and timeless aesthetics, we aim to build a wardrobe that feels like a cherished personal collection.",
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
