// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSimple from '@/components/sections/faq/FaqSimple';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqSimple
          tag="Support"
          title="Frequently Asked Questions"
          description="Common inquiries about our design process and bespoke services."
          items={[
            {
              question: "How do I book a consultation?",
              answer: "You can reach us through the contact form below, and we will schedule an appointment at our studio or virtually.",
            },
            {
              question: "How long does custom design take?",
              answer: "Depending on the complexity of the piece, bespoke designs typically take 4-8 weeks to complete.",
            },
            {
              question: "Do you ship internationally?",
              answer: "Yes, we ship our boutique items worldwide, though bespoke fittings must take place in person.",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
