// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroTiltedCards from '@/components/sections/hero/HeroTiltedCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroTiltedCards
          tag="Couture Design"
          title="Timeless Elegance by Elara"
          description="Crafting bespoke dresses that capture the essence of sophistication and grace for every modern muse."
          primaryButton={{
            text: "Explore Collections",
            href: "#collections",
          }}
          secondaryButton={{
            text: "Book Consultation",
            href: "#contact",
          }}
          items={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-woman-classic-elegant-suit-luxury-retro-vintage-woman-suit_482257-45290.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/adult-brunette-woman-violet-gown-background-old-wooden-doors_627829-8778.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/top-view-fabric-texture_23-2148882807.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/focus-sewing-machine-studio_482257-79117.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/blonde-girl-with-short-blonde-hair-poses-white-suit-room_8353-5469.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
