// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "social" section.

import React from 'react';
import SocialProofMarquee from '@/components/sections/social-proof/SocialProofMarquee';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function SocialSection(): React.JSX.Element {
  return (
    <div id="social" data-section="social">
        <SectionErrorBoundary name="social">
              <SocialProofMarquee
          tag="Featured In"
          title="Editorial Recognition"
          description="As seen in leading global fashion publications."
          names={[
            "Vogue Italia",
            "Harper's Bazaar",
            "ELLE Magazine",
            "Marie Claire",
            "L'Officiel",
            "Glamour",
            "InStyle",
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
