// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialMarqueeCards from '@/components/sections/testimonial/TestimonialMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialMarqueeCards
          tag="Clients"
          title="What They Say"
          description="Stories from women who have experienced the quality of our boutique designs."
          testimonials={[
            {
              name: "Elena V.",
              role: "Architect",
              quote: "The fit and the fabric of my custom gown were truly impeccable.",
              imageSrc: "http://img.b2bpic.net/free-photo/cute-young-woman-outdoor_624325-2459.jpg",
            },
            {
              name: "Sarah P.",
              role: "Journalist",
              quote: "I felt so confident at the gala; Elara really understands silhouettes.",
              imageSrc: "http://img.b2bpic.net/free-photo/smiley-woman-trying-out-new-clothes_23-2148660713.jpg",
            },
            {
              name: "Chloe M.",
              role: "Designer",
              quote: "Such a beautiful experience, from consultation to the final fitting.",
              imageSrc: "http://img.b2bpic.net/free-photo/cheerful-relaxed-young-businessman-showing-ok-gesture-talking-cell-phone-cafe_1391-609.jpg",
            },
            {
              name: "Priya K.",
              role: "Consultant",
              quote: "Elegant designs that always draw so many compliments.",
              imageSrc: "http://img.b2bpic.net/free-photo/happy-excited-female-shoppers-sitting-together-using-tablet-discussing-clothes-purchases-fashion-store-copy-space-consumerism-shopping-concept_74855-11776.jpg",
            },
            {
              name: "Sophia L.",
              role: "Art Curator",
              quote: "The perfect balance of modern and classic, love every piece.",
              imageSrc: "http://img.b2bpic.net/free-photo/beautiful-woman-portrait-close-up_93675-131508.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
